name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-x86 qemu-utils ovmf
        
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential nasm python3 python3-pip
        
    - name: Build BIOS version
      run: |
        make bios
        
    - name: Test BIOS version in QEMU
      run: |
        make test-bios || (echo "BIOS test failed" && exit 1)
        
    - name: Install EDK2 for UEFI build
      run: |
        sudo apt-get install -y uuid-dev gcc-aarch64-linux-gnu gcc-riscv64-linux-gnu
        git clone --depth 1 https://github.com/tianocore/edk2.git
        cd edk2
        git submodule update --init
        make -C BaseTools
        . edksetup.sh
        
    - name: Build UEFI version
      run: |
        cd edk2
        build -a X64 -p BloodHorn/BloodHorn.dsc -t GCC5
        
    - name: Test UEFI version in QEMU
      run: |
        make test-uefi || (echo "UEFI test failed" && exit 1)
