name: EDK2 Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          uuid-dev \
          nasm \
          acpica-tools \
          python3-distutils \
          qemu-system-x86 \
          ovmf \
          git \
          gcc-aarch64-linux-gnu \
          gcc-riscv64-linux-gnu
    
    - name: Set up EDK2
      run: |
        # Clone EDK2
        git clone --depth 1 https://github.com/tianocore/edk2.git
        cd edk2
        git submodule update --init
        
        # Build base tools
        make -C BaseTools
        
        # Set up environment
        export EDK_TOOLS_PATH=$(pwd)/BaseTools
        export PACKAGES_PATH=$(pwd):$(pwd)/../
        . edksetup.sh
        
        # Build BloodHorn
        build -a X64 -p BloodHorn/BloodHorn.dsc -t GCC5
        
        # Verify build output
        if [ ! -f "Build/BloodHorn/DEBUG_GCC5/X64/BloodHorn.efi" ]; then
          echo "Error: EFI binary not found"
          exit 1
        fi
        
        # Create output directory
        mkdir -p ../output/EFI/BOOT
        cp Build/BloodHorn/DEBUG_GCC5/X64/BloodHorn.efi ../output/EFI/BOOT/BOOTX64.EFI
        
        # Create test ISO
        cd ..
        xorriso -as mkisofs -e EFI/BOOT/BOOTX64.EFI -no-emul-boot -o BloodHorn.iso output/
    
    - name: Test in QEMU
      run: |
        timeout 30s qemu-system-x86_64 \
          -bios /usr/share/ovmf/OVMF.fd \
          -cdrom BloodHorn.iso \
          -m 512 \
          -vga std \
          -nographic \
          -monitor none \
          -serial stdio || \
        (echo "QEMU test completed (timeout is expected)" && exit 0)
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bloodhorn-efi
        path: |
          BloodHorn.iso
          edk2/Build/BloodHorn/DEBUG_GCC5/X64/BloodHorn.efi
