name: UEFI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc-mingw-w64-x86-64 \
          binutils-mingw-w64-x86-64 \
          gnu-efi \
          ovmf \
          qemu-system-x86 \
          xorriso \
          mtools
        
    - name: Build UEFI bootloader
      run: |
        make uefi
        
    - name: Create bootable ISO
      run: |
        make iso
        
    - name: Test in QEMU (basic boot test)
      run: |
        timeout 30s qemu-system-x86_64 \
          -bios /usr/share/ovmf/OVMF.fd \
          -cdrom BloodHorn.iso \
          -m 512 \
          -vga std \
          -nographic \
          -monitor none \
          -serial stdio || \
        (echo "QEMU test completed (timeout is expected)" && exit 0)
        
    - name: Verify EFI binary
      run: |
        if [ ! -f "build/BloodHorn.efi" ]; then
          echo "Error: EFI binary not found"
          exit 1
        fi
        echo "EFI binary built successfully"
